### PR TITLE
Use custom pre for blocks of code

### PR DESCRIPTION
**Pull request by danhartley**
A small change but do you agree?

I've added styling (copied from Wikipedia) for the pre element to differentiate code blocks.

### CODE REVIEW

**Review by jpdrecourt — COMMENTED** [review]
I like the idea of <pre> but according to MDN, I think it should be a wrapper for <code> instead of just on its own.  https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre

**Comment by danhartley** [comment]
Agreed, I've added a `<code>` block for its semantic value, and removed the custom styling for `<code>`.

`<pre>` is often used as a wrapper but it can be used on its own.

**Review by jpdrecourt — APPROVED** [review]

**Comment by jpdrecourt** [comment]
Great! Thanks for this, it made me explore the standard/MDN.

**Comment by danhartley** [comment]
Great, thanks. A good PR - small, a good review, and we both learned something.

**Pull request merged**
