### PR TITLE
Links css

### PR DESCRIPTION
**Pull request by jpdrecourt**
An attempt at link state management
I had to use a script to manage the visited sites for the READ marker because browser privacy prevents using `:before` on visited links.

### CODE REVIEW

**Review by danhartley — COMMENTED** [review]
I'm not sure about this. 

- The appearance is different in Safari than FF and Chrome, at least on a mac.
- For me, the light grey is a little too light. 
- I wonder if we need to signal that internal links have been read,  particularly so for common links e.g. Link to home, or pages we might typically expect someone to visit more than once. In which case we'd need to add exceptions which adds further complexity.
- 'Read' is also tricky because it doesn't necessarily read as the past participle but as the imperative.
- Although the JS degrades gracefully it seems a little against our philosophy.

**Comment by jpdrecourt** [comment]
I'm not sure about the solution either.

- The READ indicator feels clunky. But the link colours aren't accessible.
Maybe an aria tag could be enough.
- We can discuss the colours and the layouts, I was trying to keep
everything monochrome.
- The fact that the appearance is different shouldn't be a problem as long
as it remains elegant.
- As for the JS, I've explored CSS only options, but the :visited
pseudoclass is very well guarded!

Let's talk about it during the meeting, it's an important aspect of our
website.

JP

________________________

e: ***@***.***
m: +351 91 622 3412

**Comment by danhartley** [comment]
Yes, let's go through it together. We can make some rules for extensions too. 

I think this discussion is a great example of how we consider problems (and learn e.g. privacy preventing the use of pseudo elements on pseudo classes).

If we introduce a non-standard practice (visitors spend more time on other sites…), can we defend it? HTML has provision for visited links by default; should we ignore that and introduce a new approach? Our site is grey scale by choice but we could (re)introduce colour. Although I can see the attraction of adding text for clarity, it currently adds clutter and, because of the pronunciation problem, it's confusing.

NB For visited links you can simply use `a:visited { … }` which will also work in Safari.

How would an aria tag help? Links work for screen readers without any additions (including announcing they have been visited). e.g. screen reader says: "Visited link, read People and Code", read pronounced /rēd/

**Comment by jpdrecourt** [comment]
I didn't have the opportunity to check how the screen reader works with
visited sites, if it mentions the fact that it's visited, then we're ok.

The `a:visited`  has restrictions in terms of what you can do with CSS. (no
`content` property for example)

I agree that this is really relevant and will inform our general design
philosophy.

JP
________________________

e: ***@***.***
m: +351 91 622 3412

**Review by danhartley — APPROVED** [review]

**Pull request merged**
